config/routes.rb
TestProject::Application.routes.draw do

  resources :fotos

  resources :posts do
    resources :comments, shallow: :true
  end

   root :to => 'home#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
  has_one :history
  # attr_accessible :title, :body
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :physician
  belongs_to :patient
  # attr_accessible :title, :body
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many: books
  attr_accessible :name
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author
  attr_accessible :name
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :body, :commenter
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :pictures, :as => :imageable
end

app/models/foto.rb
class Foto < ActiveRecord::Base
  attr_accessible :name
end

app/models/history.rb
class History < ActiveRecord::Base
  belongs_to :account
  # attr_accessible :title, :body
end

app/models/migration_test2.rb
class MigrationTest2 < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :appointments
  has_many :physicians, through: :appointments
end

app/models/physician.rb
class Physician < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :appointments
  has_many :patients, :through => :appointments
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :name

  belongs_to :imageable, polymorphic: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :name, :title
  validates :name,  :presence => true
  validates :title, :presence => true,
                    :length => { :minimum => 5 }
  has_many :comments, :dependent => :destroy
  scope :by_id,  lambda {|post_id| where("id = ?", post_id )}
end

app/models/product.rb
class Product < ActiveRecord::Base
  # attr_accessible :title, :body

has_many :pictures, :as => :imageable

end

app/models/student.rb
class Student < ActiveRecord::Base
  # attr_accessible :title, :body

  has_many :subordinates, class_name: "Student"
  						  foreign_key: :prefect_id

  belongs_to :prefect, class_name: "Student"						  
end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :title, :body
has_one :account
has_one :history, :through => :account
end

app/controllers/fotos_controller.rb
class FotosController < ApplicationController
  # GET /fotos
  # GET /fotos.json
  def index
    @fotos = Foto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fotos }
    end
  end

  # GET /fotos/1
  # GET /fotos/1.json
  def show
    @foto = Foto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @foto }
    end
  end

  # GET /fotos/new
  # GET /fotos/new.json
  def new
    @foto = Foto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @foto }
    end
  end

  # GET /fotos/1/edit
  def edit
    @foto = Foto.find(params[:id])
  end

  # POST /fotos
  # POST /fotos.json
  def create
    @foto = Foto.new(params[:foto])

    respond_to do |format|
      if @foto.save
        format.html { redirect_to @foto, notice: 'Foto was successfully created.' }
        format.json { render json: @foto, status: :created, location: @foto }
      else
        format.html { render action: "new" }
        format.json { render json: @foto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fotos/1
  # PUT /fotos/1.json
  def update
    @foto = Foto.find(params[:id])

    respond_to do |format|
      if @foto.update_attributes(params[:foto])
        format.html { redirect_to @foto, notice: 'Foto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @foto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fotos/1
  # DELETE /fotos/1.json
  def destroy
    @foto = Foto.find(params[:id])
    @foto.destroy

    respond_to do |format|
      format.html { redirect_to fotos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/fotos_helper.rb
module FotosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/fotos/_form.html.erb
<%= form_for(@foto) do |f| %>
  <% if @foto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@foto.errors.count, "error") %> prohibited this foto from being saved:</h2>

      <ul>
      <% @foto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fotos/edit.html.erb
<h1>Editing foto</h1>

<%= render 'form' %>

<%= link_to 'Show', @foto %> |
<%= link_to 'Back', fotos_path %>

app/views/fotos/index.html.erb
<h1>Listing fotos</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fotos.each do |foto| %>
  <tr>
    <td><%= foto.name %></td>
    <td><%= link_to 'Show', foto %></td>
    <td><%= link_to 'Edit', edit_foto_path(foto) %></td>
    <td><%= link_to 'Destroy', foto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Foto', new_foto_path %>

app/views/fotos/new.html.erb
<h1>New foto</h1>

<%= render 'form' %>

<%= link_to 'Back', fotos_path %>

app/views/fotos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @foto.name %>
</p>


<%= link_to 'Edit', edit_foto_path(@foto) %> |
<%= link_to 'Back', fotos_path %>